set(XENSERVER_LIBRARY_VERSION 7.6.0)

set (XENSERVER_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/third_party/xenserver/${XENSERVER_LIBRARY_VERSION}/include)
find_library(XENSERVER_LIBRARY NAMES xenserver PATHS ${CMAKE_SOURCE_DIR}/third_party/xenserver/${XENSERVER_LIBRARY_VERSION}/lib64)

if (XENSERVER_INCLUDE_DIR AND XENSERVER_LIBRARY)
    set(XENSERVER_FOUND TRUE)
endif ()